[package]
name = "serde_fmt"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[features]

[dependencies.serde]
version = "1"
features = ["std"]
default-features = false
