[package]
name = "serde_fmt"
version = "0.1.0"
authors = ["Ashley Mannix <ashleymannix@live.com.au>"]
edition = "2018"

[features]
default = ["std"]

std = ["serde/std"]

[dependencies.serde]
version = "1"
default-features = false
